spring.application.name=hospital-management
spring.datasource.url=jdbc:postgresql://aws-1-ap-southeast-1.pooler.supabase.com:5432/postgres
spring.datasource.username=postgres.tdskmyxptzdtllqasppq
spring.datasource.password=Nguyen@902993
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
server.port=8080

jwt.secret=PyBJg84mJNCl5vQU38VpwijJ6Rc4V+s65D6kKTjyCG4=
jwt.access.expiration=1800000
jwt.refresh.expiration=604800000
